//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidWPolsce_RestAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryNews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryNews()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int NewsId { get; set; }
        public string CountryId { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
